// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

type AuthPayload struct {
	Token string `json:"token"`
	User  *User  `json:"user"`
}

type LeadInput struct {
	UserEmail     string  `json:"userEmail"`
	PropertyPrice float64 `json:"propertyPrice"`
	Location      string  `json:"location"`
}

type LeadScore struct {
	Score float64 `json:"score"`
}

type LoginInput struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type Mutation struct {
}

type Property struct {
	ID          string  `json:"id"`
	Address     string  `json:"address"`
	Price       float64 `json:"price"`
	VendorName  string  `json:"vendorName"`
	Description string  `json:"description"`
}

type PropertyInput struct {
	Address     string  `json:"address"`
	Price       float64 `json:"price"`
	VendorName  string  `json:"vendorName"`
	Description string  `json:"description"`
}

type Query struct {
}

type Recommendation struct {
	ID          string  `json:"id"`
	Address     string  `json:"address"`
	Price       float64 `json:"price"`
	VendorName  string  `json:"vendorName"`
	Description string  `json:"description"`
}

type RegisterInput struct {
	Email    string  `json:"email"`
	Password string  `json:"password"`
	Role     string  `json:"role"`
	Profile  *string `json:"profile,omitempty"`
	Location *string `json:"location,omitempty"`
}

type SearchResponse struct {
	SearchQuery     *string           `json:"searchQuery,omitempty"`
	Recommendations []*Recommendation `json:"recommendations"`
}

type User struct {
	ID       string  `json:"id"`
	Email    string  `json:"email"`
	Role     string  `json:"role"`
	Profile  *string `json:"profile,omitempty"`
	Location *string `json:"location,omitempty"`
}

type UserPreferences struct {
	Profile  string `json:"profile"`
	Location string `json:"location"`
}

type VendorInput struct {
	Name string `json:"name"`
	ID   string `json:"id"`
}

type VerificationResult struct {
	Status string `json:"status"`
}
